language: android
jdk:
  - oraclejdk7
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-android-m2repository
before_install:
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
script:
  - ./gradlew test --continue
after_success:
 - ./gradlew jacocoTestReport coveralls
